[package]
name = "dupels-c-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "dupels_c_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
dupels-lib = { path = "../dupels-lib" }
libc = "0.2"

[build-dependencies]
cbindgen = "0.24"
