name: dupels-ci

on:
  push:
    branches: ["*"]
    tags: ["v*"] # Run workflows on version tags
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Build (debug)
        run: cargo build --workspace --verbose

      - name: Run tests
        run: cargo nextest run --all --no-fail-fast

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --out Xml --exclude-files dupels-cli/src/main.rs

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: cobertura.xml

  build:
    name: Build and Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set short OS name
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "OSNAME=linux" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "OSNAME=windows" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "OSNAME=macos" >> $GITHUB_ENV
          fi

      - name: Install GNU toolchain (Windows only)
        if: matrix.os == 'windows-latest'
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build CLI and GUI (release)
        shell: bash
        run: |
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              cargo build --release --target x86_64-pc-windows-gnu
            else
              cargo build --release
            fi

      - name: Prepare CLI artifacts (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          set -e
          PKG="dupels-${OSNAME}"
          mkdir "$PKG"
          cp target/release/dupels "$PKG/"
          zip -r "${PKG}.zip" "$PKG"
          tar czf "${PKG}.tar.gz" "$PKG"

      - name: Prepare GUI artifacts (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          set -e
          PKG="dupels-gui-${OSNAME}"
          mkdir "$PKG"
          cp target/release/dupels-gui "$PKG/"
          zip -r "${PKG}.zip" "$PKG/"
          tar czf "${PKG}.tar.gz" "$PKG/"

      - name: Prepare CLI artifacts (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $PKG = "dupels-$env:OSNAME"
          mkdir $PKG
          Copy-Item target/x86_64-pc-windows-gnu/release/dupels.exe $PKG/
          Compress-Archive -Path "$PKG\*" -DestinationPath "$PKG.zip"
          tar -czf "$PKG.tar.gz" $PKG

      - name: Prepare GUI artifacts (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $PKG = "dupels-gui-$env:OSNAME"
          mkdir $PKG
          Copy-Item target/x86_64-pc-windows-gnu/release/dupels-gui.exe $PKG/
          Compress-Archive -Path "$PKG\*" -DestinationPath "$PKG.zip"
          tar -czf "$PKG.tar.gz" $PKG

      - name: Upload CLI zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: dupels-${{ env.OSNAME }}-zip
          path: dupels-${{ env.OSNAME }}.zip

      - name: Upload GUI zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: dupels-gui-${{ env.OSNAME }}-zip
          path: dupels-gui-${{ env.OSNAME }}.zip

      - name: Upload CLI tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: dupels-${{ env.OSNAME }}-tar
          path: dupels-${{ env.OSNAME }}.tar.gz

      - name: Upload GUI tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: dupels-gui-${{ env.OSNAME }}-tar
          path: dupels-gui-${{ env.OSNAME }}.tar.gz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, build-c-ffi, coverage, test]
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List downloaded artifacts
        run: find dist -type f -name "*.zip" -o -name "*.tar.gz" | head -20

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.zip
            dist/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
